---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: NodePort
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 5050
      targetPort: 5050
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: rest
          image: vad1mo/hello-world-rest:latest
          ports:
            - containerPort: 5050

